chore: fix staticcheck issues (#164)
Use [staticcheck](https://staticcheck.dev/) to find and fix correctness
issues.

	❯ go run honnef.co/go/tools/cmd/staticcheck@latest ./...
	internal/iptables/iptables.go:61:3: should replace loop with rules = append(rules, EgressNetworkPolicyToIpTableRules(policy, peerChain)...) (S1011)
	internal/iptables/iptables.go:80:22: unnecessary use of fmt.Sprintf (S1039)
	internal/it/suite_test.go:32:5: var cfg is unused (U1000)
	internal/it/suite_test.go:34:5: var testEnv is unused (U1000)
	internal/it/suite_test.go:172:2: this value of b is never used (SA4006)
	internal/it/suite_test.go:185:2: this value of b is never used (SA4006)
	internal/it/suite_test.go:222:2: this value of err is never used (SA4006)
	pkg/api/v1alpha1/wireguard_types.go:26:2: only the first constant in this group has an explicit type (SA9004)
	pkg/controllers/suite_test.go:41:5: var cfg is unused (U1000)
	pkg/controllers/wireguard_controller.go:151:13: error strings should not be capitalized (ST1005)
	pkg/controllers/wireguard_controller.go:407:3: this value of port is never used (SA4006)
	pkg/controllers/wireguard_controller.go:407:10: Sprint doesn't have side effects and its return value is ignored (SA4017)
	pkg/wireguard/wireguard.go:63:2: this value of err is never used (SA4006)
	pkg/wireguard/wireguard.go:104:2: this value of link is never used (SA4006)
	pkg/wireguard/wireguard.go:155:2: this value of err is never used (SA4006)
	pkg/wireguard/wireguard.go:293:6: should omit comparison to bool constant, can be simplified to peer.Spec.Disabled (S1002)
	pkg/wireguard/wireguard.go:343:2: this value of err is never used (SA4006)
	exit status 1

Refs: #160